// flow-typed signature: 0d0ffd1e72313aa054d9bc5e19925b9e
// flow-typed version: <<STUB>>/webpack-cli_v^2.0.14/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}
